config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :create, :show, :new] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian),}
  validates :name, :category, :address, presence: true
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, numericality: { only_integer: true }, inclusion: 0..5
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<nav class="navbar navbar-light bg-light">
  <a href="restaurants/new" class="navbar-brand">Create New</a>
  <a href="restaurants" class="navbar-brand">See All Restaurants</a>
</nav>
<h1>Restaurants</h1>

<% @restaurants.each do |restaurant| %>
<%=link_to restaurant.name, restaurant_path(restaurant), class:"btn btn-light btn-rouded"%>
<br>
<% end %>

app/views/restaurants/new.html.erb
<%= simple_form_for [ @restaurant ] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, :collection => %w[chinese italian japanese french belgian]%>
  <%= f.submit "Submit Restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<nav class="navbar navbar-light bg-light">
  <a href="/new" class="navbar-brand">Create New</a>
  <a href="/restaurants" class="navbar-brand">See All Restaurants</a>
</nav>
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>

<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %> Rated:<%= review.rating %>/5</li>
  <% end %>
</ul>

<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant),  class: "btn btn-primary" %>

<%= link_to 'Back', restaurants_path, class: "btn btn-primary" %>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit Restaurant", class: "btn btn-primary" %>
<% end %>